export const DataList = [
    {
        id:1,
        image:'./images/atcommerce.png',
        link:'http://atcommerce.pk/home/'
    },
    {
        id:2,
        image:'./images/gul.png',
        link:'http://guldemo.atcommerce.pk/'
    },
    {
        id:3,
        image:'./images/metro.png',
        link:'http://metrodemo.atcommerce.pk/'
    },
    {
        id:4,
        image:'./images/grocery.png',
        link:'http://grocerydemo.atcommerce.pk/'
    },
    {
        id:5,
        image:'./images/aibattery.png',
        link:'http://aibattery.atcommerce.pk/'
    },
    {
        id:6,
        image:'./images/auto.png',
        link:'http://autodemo.atcommerce.pk/'
    },
    {
        id:7,
        image:'./images/gitreact.png',
        link:'https://jenefir12.github.io/react-js-website'
    }
]